# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_manager', '0002_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDisp', models.DateField()),
                ('advOrTrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialog_manager.Response')),
            ],
        ),
        migrations.CreateModel(
            name='Not_answer_messege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answ', models.TextField()),
                ('date_answ', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.ManyToManyField(to='dialog_manager.Intent')),
                ('listRespons', models.ManyToManyField(to='dialog_manager.Response')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='not_answer_messege',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialog_manager.Users'),
        ),
        migrations.AddField(
            model_name='displayedmessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialog_manager.Users'),
        ),
    ]
