# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_manager', '0003_auto_20171020_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Not_answer_messege',
            new_name='NotAnswerMessege',
        ),
        migrations.RenameField(
            model_name='displayedmessages',
            old_name='advOrTrain',
            new_name='adv_or_train',
        ),
        migrations.RenameField(
            model_name='displayedmessages',
            old_name='dateDisp',
            new_name='date_disp',
        ),
        migrations.RenameField(
            model_name='pair',
            old_name='listRespons',
            new_name='list_respons',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='nameUser',
            new_name='name_user',
        ),
    ]
