# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_manager', '0004_auto_20171026_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='NotAnswerMessege',
            new_name='NotAnsweredMessage',
        ),
        migrations.RenameField(
            model_name='displayedmessages',
            old_name='date_disp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='notansweredmessage',
            old_name='date_answ',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='notansweredmessage',
            old_name='text_answ',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='pair',
            old_name='list_respons',
            new_name='list_response',
        ),
    ]
