# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_manager', '0005_auto_20171026_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='intent',
            new_name='intents',
        ),
        migrations.RenameField(
            model_name='pair',
            old_name='list_response',
            new_name='responses',
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.CharField(max_length=1200),
        ),
    ]
